### ISSUE TITLE
Serve both as YAML and as JSON

### ISSUE THREAD

**Issue by slinkydeveloper** [Flowneee/okapi-operation#5]
It would be nice if we could serve the openapi both as yaml and json. This is commonly done by either using the `Accept` header, or by reading a `format=[json|yaml]` query parameter.

**Comment by Flowneee** [comment]
`Accept` seems like proper solution. Although maybe `serde_yaml` should be behind feature.

**Comment by Flowneee** [comment]
Added in 0.2.1
