### ISSUE TITLE
`Accept` is not working

### ISSUE THREAD

**Issue by slinkydeveloper** [Flowneee/okapi-operation#8]
Example:

```
!10181 ➜ http -v GET localhost:8081/openapi Accept:application/yaml    
GET /openapi HTTP/1.1
Accept: application/yaml
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8081
User-Agent: HTTPie/3.2.1



HTTP/1.1 400 Bad Request
content-length: 72
content-type: text/plain; charset=utf-8
date: Wed, 10 May 2023 08:06:34 GMT

Bad Accept header value, should be either 'json', 'yaml', '*/*' or empty
```

Seems like `application/yaml` (nor `text/yaml`) works. Both are used as yaml data types. `application/json` and `text/json` doesn't work either with same error.

**Comment by slinkydeveloper** [comment]
Nor `*/yaml` or `*/json`

**Comment by Flowneee** [comment]
Hmm, I didn't know that text/yaml or json is valid mime type. I googled and see yaml can be `yml`, `x-yaml`, `x-yml`, also there is `+yaml` https://github.com/ietf-wg-httpapi/mediatypes/blob/main/draft-ietf-httpapi-yaml-mediatypes.md.

> I can contribute a fix

Please do )

**Comment by slinkydeveloper** [comment]
My understanding from the MDN docs is that it needs to be always in the form of `type/subtype`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

Hence `application/yaml` and `text/yaml` :)
